#-------------------------------
# General Site Settings

title: Taewoo's Portfolio
logo:
author: Ahn Taewoo
description: Taewoo's personal portfolio blog.
email: taewoo997142@gmail.com
phone: +82 10 7142 6706
address: Seoul, Republic of Korea
copyright: Copyright 2022. Ahn Taewoo.

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Taewoo's personal portfolio blog

social:
- {icon: "ti-github", link: "http://www.naver.com/"}
- {icon: "ti-pinterest", link: "http://www.naver.com/"}
- {icon: "ti-instagram", link: "http://www.naver.com/"}
- {icon: "ti-facebook", link: "http://www.naver.com/"}


# About Section
blurb:
  I'm a student who dreams of becoming video artist.</br>
  This blog introduce school projects and personal works.</br>
  Using softwares: Adobe Photoshop, AfterEffect, Premiere Pro, Illustrator, Xd.

blurb-btn-link: '/about'
blurb-btn-name: know more


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Photoshop CC, color: '#31a8ff', value: '50%'}
- {name: Illustration CC, color: '#ff9a00', value: '70%'}
- {name: Premiere Pro CC, color: '#7a7acc', value: '80%'}
- {name: After Effects CC, color: '#9999ff', value: '80%'}
- {name: Camera Skills, color: '#26b1b1', value: '90%'}
- {name: MAYA, color: '#bcdadc', value: '50%'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Media Design, date: '2019 - ', organization: 'Gyeonggi University of Science and Technology, Siheung-si, Gyeonggido'}
- {name: Natural Sciences, date: '2015 - 2018', organization: 'Muan High School, Muan, Jeollanamdo'}



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/modern bathroom.jpg"
    url: "/modernbathroom"

  - image : "assets/images/portfolio/hill house_1.jpg"
    url: "/hillhouse"
    
  - image : "assets/images/portfolio/minimal bathroom_1.jpg"
    url: "/minimalbathroom"
    
  - image : "assets/images/portfolio/sunset kitchen.jpg"
    url: "/sunsetkitchen"
    
  - image : "assets/images/portfolio/studio apartment_1.jpg"
    url: "studioapartment"
    
  - image : "assets/images/portfolio/herringbone kitchen_1.jpg"
    url: "herringbonekitchen"


# Portfolio Page
portfolio-label:
- {
    title : "Video",
    type : "Video"
  }
- {
    title : "Motion Graphic",
    type : "Motion Graphic"
  }
- {
    title : "Concept Art",
    type : "Concept Art"
  }

portfolio-items:
  - image : "assets/images/portfolio/hill house_1.jpg"
    url: "/hillhouse"
    portfolio-type:
     - type: "Video"
     - type: "Concept Art"
      
  - image : "assets/images/portfolio/sunset kitchen.jpg"
    url: "/sunsetkitchen"
    portfolio-type:
      - type: "CG Art"
      
  - image : "assets/images/portfolio/herringbone kitchen_1.jpg"
    url: "/herringbonekitchen"
    portfolio-type:
      - type: "CG Art"
      
  - image : "assets/images/portfolio/minimal bathroom_1.jpg"
    url: "minimalbathroom"
    portfolio-type:
      - type: "CG Art"
      
  - image : "assets/images/portfolio/studio apartment_1.jpg"
    url: "/studioapartment"
    portfolio-type:
      - type: "CG Art"
      
  - image : "assets/images/portfolio/fantasy manipulation.jpg"
    url: "/fantasymanipulation"
    portfolio-type:
      - type: "Concept Art"
      
  - image : "assets/images/portfolio/infographic.jpg"
    url: "/infographic"
    portfolio-type:
      - type: "Concept Art"
      
  - image : "assets/images/portfolio/character redesign.jpg"
    url: "/characterredesign"
    portfolio-type:
      - type: "Concept Art"

  - image : "assets/images/portfolio/melon commercial.jpg"
    url: "/meloncommercial"
    portfolio-type:
      - type: "Video"


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: taewoo997142@gmail.com
